add_newline = false

command_timeout = 3000

[directory]
truncation_length = 100
#home_symbol = 'ï£¿ '

[line_break]
disabled = false

[docker_context]
disabled = true
#format = 'via [ğŸ‹ $context](blue bold)'

[container]
disabled = true
#format = '[$symbol \[$name\]]($style) '

[nodejs]
disabled = true

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = '#ffa500'
symbol = 'ï‚» '
# force_display = true
# disabled = false
# [aws.region_aliases]
# ap-southeast-2 = 'au'
# us-east-1 = 'va'
# [aws.profile_aliases]
# CompanyGroupFrobozzOnCallAccess = 'Frobozz'

[gcloud]
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '
style = 'blue'
symbol = 'îŸ° '
# [gcloud.project_aliases]
# very-long-project-name = 'vlpn'

[git_branch]
symbol = 'ğŸŒ± '
truncation_symbol = 'î‚  '
ignore_branches = ['master', 'main']

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
format = '([\[$ahead_behind$all_status\]]($style) )'
ahead = 'â¬†ï¸${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â¬‡ï¸${count}'
untracked = ''
style = 'blue'

