add_newline = false

command_timeout = 5000
scan_timeout = 2000

[character]
vimcmd_symbol = '[V](bold green) '

[directory]
truncation_length = 10
truncation_symbol = 'ÔÅº '
# git repository„Åß„ÇÇ„Éï„É´„Éë„Çπ„ÇíË°®Á§∫
# truncate_to_repo = false
home_symbol = '~'
read_only = 'Û∞åæ '
format = """
[$path]($style)\
[$read_only]($read_only_style) \
"""
style = 'bold fg:#80EBDF'
read_only_style = 'bold red'

[fill]
symbol = '-'
style = 'bold white'

[line_break]
disabled = false

[docker_context]
disabled = true
#format = 'via [üêã $context](blue bold)'

[container]
disabled = true
#format = '[$symbol \[$name\]]($style) '

[nodejs]
disabled = true

[aws]
format = '[ÓÇ∂](bg:#24283b fg:#8f5736)[$symbol($profile)(\($project\))(\($region\))]($style)[ÓÇ¥](bg:#24283b fg:#8f5736)'
# style = '#ffa500'
style = 'fg:white bg:#8f5736'
symbol = 'Ôâ∞'
# force_display = true
# disabled = false
# [aws.region_aliases]
# ap-southeast-2 = 'au'
# us-east-1 = 'va'
# [aws.profile_aliases]
# CompanyGroupFrobozzOnCallAccess = 'Frobozz'

[gcloud]
# format = 'on [$symbol$account(@$domain)(\($project\))]($style) '
format = '[ÓÇ∂](bg:#24283b fg:#3a6494)[$symbol($profile)(\($project\))(\($region\))]($style)[ÓÇ¥](bg:#24283b fg:#3a6494)'
style = 'fg:white bg:#3a6494'
symbol = 'Óü∞'
# [gcloud.project_aliases]
# very-long-project-name = 'vlpn'

[git_branch]
symbol = "Ôêò"
# ignore_branches = ['master', 'main']
style = "fg:purple bg:#121211"
format = """
[ÓÇ∫](fg:#121211)\
[$symbol $branch]($style)\
"""

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
ahead = '‚¨ÜÔ∏é${count}'
diverged = '‚áï‚á°${ahead_count}‚á£${behind_count}'
behind = '‚¨áÔ∏é${count}'
untracked = ''

style = "fg:purple bg:#121211"
format = """
[$all_status$ahead_behind]($style)\
[ÓÇº](fg:#121211)\
"""

[cmd_duration]
# min_time = 2
# show_milliseconds = true
format = ' took [$duration]($style)'
