# ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆå‰ã®æ”¹è¡Œã‚’ç„¡åŠ¹åŒ–
add_newline = false

# ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªã‚’2è¡Œç›®ã«ç§»å‹•
# format = """
# $all\
# $fill\
# $cmd_duration\
# \n$character
# """
# format = '$all$fill$line_break$character'
format = '$directory$git_branch$git_status$aws$gcloud$line_break$character'

command_timeout = 5000
scan_timeout = 2000

[line_break]
disabled = false

[character]
vimcmd_symbol = '[V](bold green)'

[directory]
truncation_length = 10
truncation_symbol = 'ï¼ '
# git repositoryã§ã‚‚ãƒ•ãƒ«ãƒ‘ã‚¹ã‚’è¡¨ç¤º
# truncate_to_repo = false
home_symbol = '~'
read_only = 'ó°Œ¾ '
format = """
[$path]($style)\
[$read_only]($read_only_style)\
"""
style = 'bold fg:#80EBDF'
read_only_style = 'bold red'

[fill]
symbol = 'â”€'
style = '#4d4d4d'

[docker_context]
disabled = true
#format = 'via [ğŸ‹ $context](blue bold)'

[container]
disabled = true
#format = '[$symbol \[$name\]]($style) '

[aws]
format = '[î‚¶](fg:#583622)[$symbol($profile)(\($project\))(\($region\))]($style)[î‚´](fg:#583622)'
# style = '#ffa500'
style = 'fg:white bg:#583622'
symbol = 'ï‰°'
# force_display = true
# disabled = false
# [aws.region_aliases]
# ap-southeast-2 = 'au'
# us-east-1 = 'va'
# [aws.profile_aliases]
# CompanyGroupFrobozzOnCallAccess = 'Frobozz'

[gcloud]
# format = 'on [$symbol$account(@$domain)(\($project\))]($style) '
format = '[î‚¶](fg:#28405c)[$symbol($profile)(\($project\))(\($region\))]($style)[î‚´](fg:#28405c)'
style = 'fg:white bg:#28405c'
symbol = 'îŸ°'
# [gcloud.project_aliases]
# very-long-project-name = 'vlpn'

[git_branch]
symbol = "ï˜"
# ignore_branches = ['master', 'main']
style = "fg:#cccc56 bg:#2b2b29"
format = """
[î‚º](fg:#2b2b29)\
[$symbol $branch]($style)\
"""

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
ahead = 'â¬†ï¸${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â¬‡ï¸${count}'
untracked = ''

style = "fg:#cccc56 bg:#2b2b29"
format = """
[$all_status$ahead_behind]($style)\
[î‚¼](fg:#2b2b29)\
"""

[cmd_duration]
# min_time = 2
# show_milliseconds = true
format = ' took [$duration]($style)'

